<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

// Adds `before content` widget area
add_action('genesis_before_content', 'before_content_widget');
function before_content_widget() {
	if ( is_front_page() ) {
		echo '<div class="before-content-widget-area">';
			dynamic_sidebar('before-content');
		echo '</div>';
	}
}

// Initialize Genesis.
genesis();